# Generated by Django 2.0 on 2018-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
